name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python_version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf autogen libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev ant
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build with Buildozer
        run: |
          # Указываем Buildozer использовать предустановленный Android SDK
          export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
          export ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME
          yes | buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Qsl-VPN-Ready
          path: bin/*.apk
